Adapted to bun logging options
oiime/logrusbun pull request #3
Opened 2024-08-12 08:59 UTC by jernsting

2024-08-12 14:21 UTC, oiime requested changes
Would it be possible to reflect the changes in the README and testing?

2024-08-13 06:22 UTC, jernsting commented
Added documentation in readme and tests in testing (following your testing scheme).

2024-10-11 11:28 UTC, oiime approved these changes

2024-10-11 11:28 UTC, merged

2025-05-15 19:30 UTC, jernsting commented
Could you please provide a new release to distribute the new implementation?